// import nodemailer from "nodemailer";

// export const sendMail = async (to, subject, text) => {
//     try {
//             const transporter = nodemailer.createTransport({
//                 host: process.env.MAILTRAP_SMTP_HOST,
//                 port: process.env.MAILTRAP_SMTP_PORT,
//                 secure: false, // true for 465, false for other ports
//                 auth: {
//                 user: process.env.MAILTRAP_SMTP_USER,
//                 pass: process.env.MAILTRAP_SMTP_PASS,
//                 },
//             });
//             const info = await transporter.sendMail({
//                 from: 'Inggest TNS',
//                 to,
//                 subject,
//                 text, 
//             });
//             console.log("Message sent:", info.messageId);
//             return info;
//     } catch (error) {
//         console.error('❌ Error sending email:', error.message);
//         throw error;
//     }
// }


import nodemailer from "nodemailer";

export const sendMail = async (to, subject, text) => {
    try {
        const transporter = nodemailer.createTransport({
            host: 'smtp.gmail.com', // ✅ Change 1: Use Gmail's SMTP host
            port: 465,             // ✅ Change 2: Use the standard secure port
            secure: true,          // ✅ Change 3: Set secure to true
            auth: {
                // ✅ Change 4: Use your Gmail address
                user: process.env.GMAIL_USER, 
                // ✅ Change 5: Use the App Password generated by Google
                pass: process.env.GMAIL_APP_PASSWORD, 
            },
        });
        
        // You should change the 'from' address to match the GMAIL_USER 
        // for better deliverability
        const info = await transporter.sendMail({
            from: process.env.GMAIL_USER, // Set 'from' to your authenticated Gmail address
            to,
            subject,
            text, 
        });
        
        console.log("Message sent:", info.messageId);
        return info;
    } catch (error) {
        console.error('❌ Error sending email:', error.message);
        throw error;
    }
}